config/routes.rb
Rails.application.routes.draw do

  resources :products

  put 'products/:id/toggle_pro' => 'products#toggle_pro', as: :toggle_pro_product

  put 'order/:id' => 'orders#order', as: :order_product

  root 'pages#welcome'

  devise_for :users, controllers: { registrations: "users/registrations" }
  

end

app/models/product.rb
# Simple product model. Products has name, description and photo
class Product < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true, length: { maximum: 42 }
  validates :photo, presence: true, on: :create
  validates :user, presence: true

  has_attached_file :photo, styles: { medium: '450x450>', thumb: '100x100#' },
                            default_url: '/images/:style/missing.png',
                            url: '/images/:hash.:extension',
                            hash_secret: 'da9a3c0d2aaf25d6bb627051fd2cf9a4'
  validates_attachment_content_type :photo, content_type: %r{\Aimage\/.*\Z}
  validates_attachment_size :photo, less_than: 4.megabytes

  def pro?
    pro
  end
end

app/controllers/products_controller.rb
# Products controller. Show, add, edit, delete products by user.
class ProductsController < ApplicationController
  helper UsersHelper

  before_action :authenticate_user!,
                only: [:new, :create, :edit, :update, :destroy]
  before_action :check_access, only: [:edit, :update, :destroy]
  before_action :owner?, only: [:new, :create]

  def index
    @products = Product.all if user_signed_in?
    @products = Product.where(pro: false) unless user_signed_in?
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.valid? && @product.save
      redirect_to @product
    else
      @error_messages = @product.errors.full_messages
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to @product
    else
      @error_messages = @product.errors.full_messages
      render 'edit'
    end
  end

  def toggle_pro
    redirect_to products_url unless current_user.admin?

    @product = Product.find(params[:id])
    @product.pro = !@product.pro
    @product.save
    redirect_to @product
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to products_url
  end

  protected

  def check_access
    @product = Product.find(params[:id])
    redirect_to products_url unless current_user.id == @product.user_id
  end

  def owner?
    return true if current_user.owner?
    flash[:error] = 'Только владельцы котоферм могут добавлять котиков'
    redirect_to products_url
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :photo, :pro)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<li class="col-xs-6 col-sm-4 col-md-2">

<% if current_user == product.user %>
<div class="actions btn-group-vertical" role="group">
  <%= link_to edit_product_path(product), title: 'Редактировать', class: 'btn btn-default btn-xs' do %>
  <i class="glyphicon glyphicon-pencil"></i>
  <% end %>
  <%= link_to product_path(product), method: 'delete', title: 'Уничтожить', class: 'btn btn-default btn-xs' do %>
  <i class="glyphicon glyphicon-trash"></i>
  <% end %>
</div>
<% end %>

<% if user_signed_in? && current_user.admin? %>
  <div class="actions btn-group-vertical" role="group">
    <%= link_to toggle_pro_product_path(product),
                title: 'Бро или не бро?',
                method: 'put',
                class: 'btn btn-default btn-xs' do %>
      <i class="glyphicon glyphicon-star"></i>
    <% end %>
  </div>
<% end %>

  <%= link_to product do %>
    <%= image_tag product.photo.url(:thumb), alt: product.name, title: product.name %><br> 
    <%= product.name %>
  <% end %>
  <% if product.pro? %>
    <br>
    <strong><i class="glyphicon glyphicon-star"></i> БРО</strong>
  <% end %>

</li>

app/views/products/_product_form.html.erb
<%= form_for @product, html: {class: 'form-horizontal', multipart: true} do |f| %>
<div class='form-group'>
  <%= f.label :name, 'Имя котика', class: 'col-sm-2 control-label' %>
  <div class='col-sm-10'>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Имя котика' %>
  </div>
</div>

<div class='form-group'>
  <%= f.label :description, 'Описание котика', class: 'col-sm-2 control-label' %>
  <div class='col-sm-10'>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Описание котика', rows: 5 %>
  </div>
</div>

<div class='form-group'>
  <%= f.label :photo, 'Фото котика', class: 'col-sm-2 control-label' %>
  <div class='col-sm-10'>
    <%= f.file_field :photo %>
  </div>
</div>

<div class='form-group'>
  <div class='col-sm-offset-2 col-sm-10'>
    <% if action_name == 'new' || action_name == 'create' %>
      <%= f.submit 'Добавить котика', class: 'btn btn-success' %>
    <% elsif action_name == 'edit' || action_name == 'update' %>
      <%= f.submit 'Изменить котика', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>
<% end %>

app/views/products/edit.html.erb
<h1>Редактирование котика <%= @product.name %></h1>

<%= render 'product_form' %>

app/views/products/index.html.erb
<h1>Посмотрите наш замечательный котолог</h1>

<ul class="row products-list">
  <%= render @products %>
</ul>

app/views/products/new.html.erb
<h1>Добавление котика на ферму <%= current_user.store_name %></h1>

<%= render 'product_form' %>

app/views/products/show.html.erb
<% if @product.pro? && !user_signed_in? %>

  <h1>Вы должны быть
    <%= link_to 'зарегистрированы', new_user_registration_path %>
    для просмотра этого котика</h1>
  <h2>Этот котик — БРО</h2>

<% else %>

<h1>
  Котик <%= @product.name %>
  <% if @product.pro? %>
    <i class="glyphicon glyphicon-star"></i> БРО
  <% end %>
</h1>

<% if current_user == @product.user %>
<div class="actions btn-group-vertical" role="group">
  <%= link_to edit_product_path(@product), title: 'Редактировать', class: 'btn btn-default btn-xs' do %>
  Редактировать <i class="glyphicon glyphicon-pencil"></i>
  <% end %>
  <%= link_to product_path(@product), method: 'delete', title: 'Уничтожить', class: 'btn btn-default btn-xs' do %>
  Уничтожить <i class="glyphicon glyphicon-trash"></i>
  <% end %>
</div>
<% end %>

<% if user_signed_in? && current_user.admin? %>
<div class="actions btn-group-vertical" role="group">
  <%= link_to toggle_pro_product_path(@product),
              title: 'Сделать про',
              method: 'put',
              class: 'btn btn-default btn-xs' do %>
    <% if @product.pro? %>
      Не бро
    <% else %>
      Бро
    <% end %>
    <i class="glyphicon glyphicon-star"></i>
  <% end %>
</div>
<% end %>

<% if user_signed_in? && current_user.guest? && !@product.pro? %>
<div class="actions btn-group-vertical" role="group">
  <%= link_to order_product_path(@product),
              title: 'Купить котеньку',
              method: 'put',
              class: 'btn btn-default btn-xs' do %>
    Купить котеньку
    <i class="glyphicon glyphicon-shopping-cart"></i>
  <% end %>
</div>
<% end %>


<%= image_tag @product.photo.url(:medium) %>

<div class='description'>
  <%= @product.description %> 
</div>

<div class="author">
  <strong>Автор:</strong> <%= (@product.user.name != '') ? @product.user.name : @product.user.email %>
</div>

<% if user_signed_in? && (current_user.admin? || current_user.owner?) %>
<div class="author-shop">
  <strong>Котоферма:</strong> <%= @product.user.store_name %>
</div>
<% end %>

<% end %>