config/routes.rb
Rails.application.routes.draw do

  resources :products

  put 'products/:id/toggle_pro' => 'products#toggle_pro', as: :toggle_pro_product

  put 'order/:id' => 'orders#order', as: :order_product

  root 'pages#welcome'

  devise_for :users, controllers: { registrations: "users/registrations" }
  

end

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>

<% if current_user.owner? || current_user.admin? %>
  <%= image_tag current_user.avatar.url(:thumb) %>
<% else %>
  <%= gravatar_for current_user, size: 100,
                   style: 'vertical-align: top; text-align: left' %>
<% end %>

<h4>
  <%= current_user.name != '' ? current_user.name : current_user.email %>
  <% if current_user.owner? %>
    <br>
    <%= current_user.store_name %>
  <% end %>
</h4>

<ul class="list-unstyled">
  <li><%= link_to 'Редактировать профиль', edit_user_registration_path %></li>
  <% if current_user.owner? %>
  <li><%= link_to 'Добавить котика', new_product_path %></li>
  <% end %>
  <li><%= link_to 'Все котики', products_path %></li>
  <li><%= link_to 'Выйти к чертям', destroy_user_session_path,
                  method: 'delete' %></li>
</ul>

<% else %>

  <h2>Log in</h2>

  <%= form_for(:user, url: session_path(:user)) do |f| %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>

    <div class="actions">
      <%= f.submit "Log in" %>
    </div>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>TinyCat &mdash; ваш лучший котолог!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#navbar" aria-expanded="false"
          aria-controls="navbar">
        <span class="sr-only">Меню</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Tiny Cat', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <p class="navbar-text navbar-right">
          Мяу, <%= link_to (
                        current_user.name != '' ? current_user.name
                        : current_user.email
                      ), root_path, class: 'navbar-link',
                      title: 'Поделиться котятками' %>
          <%= link_to '<i class="glyphicon glyphicon-log-out"></i>'.html_safe,
                destroy_user_session_path, class: 'navbar-link',
                title: 'Уйти прочь', method: 'delete' %>
        </p>
      <% else %>
      <%= form_for(:user, :url => session_path(:user), html: 
              {class: 'navbar-form navbar-right'}) do |f| %>
        <div class="form-group">
          <%= f.text_field :email, class: 'form-control', placeholder: 'E-mail' %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class: 'form-control',
                placeholder: 'Пароль' %>
        </div>
        <%= f.submit 'Войти', class: 'btn btn-success' %>
      <% end %>
      <% end %>
    </div>
  </div>
</nav>

<% if notice || alert || @error_messages || !flash.empty? %>
<div class="container flashes">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-6">
      <div class='flashes'>
        <% if notice || !flash.empty? %>
        <div class='flash notice alert alert-success alert-dismissible fade in'>
          <button type="button" class="close" data-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
          <% flash.each do |name, msg| -%>
            <%= content_tag :p, msg, class: name %>
          <% end -%>
        </div>
        <% elsif alert || @error_messages %>
        <div class='flash alert alert-danger alert-dismissible fade in'>
          <button type="button" class="close" data-dismiss="alert" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
          <p><%= alert %></p>
          <% if @error_messages %>
          <ul>
            <% @error_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

<% unless controller_name == 'pages' %>
<div class="container">
  <div class="row">
    <div class="col-md-9">
<%= yield %>
    </div>

    <div class="col-md-3 text-right">

      <%= render 'layouts/sidebar' %>

    </div>
  </div>
</div>
<% else %>
<%= yield %>
<% end %>

<footer class="footer">
  <div class="container">
    <p class="text-muted">&copy;&nbsp;2015 Tiny Cat inc.</p>
  </div>
</footer>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>